# Generated by Django 3.1.5 on 2021-03-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_name', models.CharField(max_length=100)),
                ('order_address', models.CharField(max_length=100)),
                ('order_destination', models.CharField(max_length=100)),
                ('order_email_address', models.CharField(max_length=100)),
                ('order_phone_phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
